### ISSUE TITLE
`LocalAlloc()` in `AuthenticodeDigestSign()`

### ISSUE THREAD

**Issue by jozefizso** [namazso/AzuKI#1]
Hi,
I read the documentation for [PFN_AUTHENTICODE_DIGEST_SIGN callback function](https://learn.microsoft.com/en-us/windows/win32/seccrypto/pfn-authenticode-digest-sign) - which should be the `AuthenticodeDigestSign()` function and they have this notice about signed digest data:

> The parameter `pSignedDigest->pbData` must be allocated by calling `HeapAlloc` passing the result of `GetProcessHeap()` as the first parameter.

You implementation is using `LocalAlloc()` function to return the signed digest. Is this implementation correct?

**Comment by namazso** [comment]
Yes, you can check that it does the same thing (HeapAlloc == RtlAllocateHeap, it's a forward):

![image](https://github.com/namazso/AzuKI/assets/8676443/d00bd5e6-9089-473d-a94f-e2547e7c7a51)

Though I might change it to be more in-line with the docs
